#!/bin/bash

21driver() {
    echo "Instalando pacote de versões do PHP ao repositório"
    sudo add-apt-repository ppa:ondrej/php

    echo "INSTALANDO PHP7.4.33 E MÓDULOS NECESSÁRIOS"
    sudo apt install php7.4 && sudo apt install php7.4-mbstring php7.4-curl php7.4-xml php7.4-intl php7.4-gd php7.4-gmp && sudo apt upgrade && sudo apt update && sudo apt dist-upgrade

    echo "HABILITE A VERSÃO 7.4 DO PHP"
    sudo update-alternatives --config php

    echo "PHP INSTALADO. INSTALANDO COMPOSER"
    sudo apt install composer
    
    echo "COMPOSER INSTALADO. CRIANDO LARAVEL APP"
    composer create-project laravel/laravel 21-driver-dev && cd 21-driver-dev

    echo "INSTALANDO DEPENDÊNCIAS DO COMPOSER"
    composer install

    echo "INICIANDO APLICAÇÃO..."
    php artisan serve

    nodejs
}

nodejs() {
    while true; do
        read -p "DESEJA INSTALAR O NODEJS? " sn
        case $sn in
            [Ss]* ) //sudo apt install npm; break;;
            [Nn]* ) exit;;
            * ) echo "Por favor responda sim ou não.";;
        esac
    done
}

21driver
